---
title: "2_Merge_normalization_clustering"
output: html_document
date: "2023-08-08"
---
# Import individual samples
```{r Chicken_LV_1_8}
# Define the list of sample names
sample_names <- paste0("LV_", 1:8)

# Loop through the sample names and process each sample
results <- list()

for (sample in sample_names) {
  result <- JS_QC_individual(sample, datapath, savepath_rds) # Process each sample using JS_QC_individual
  results[[sample]] <- result  # Store results for each sample in a list
}
```
# QC, merge and major lineage interpretation
```{r remove_doublets}
# Read and process each dataset
dataset_paths <- list(
  LV_1 = paste0(savepath_rds, "adj.LV_1.rds"),
  LV_2 = paste0(savepath_rds, "adj.LV_2.rds"),
  LV_3 = paste0(savepath_rds, "adj.LV_3.rds"),
  LV_4 = paste0(savepath_rds, "adj.LV_4.rds"),
  LV_5 = paste0(savepath_rds, "adj.LV_5.rds"),
  LV_6 = paste0(savepath_rds, "adj.LV_6.rds"),
  LV_7 = paste0(savepath_rds, "adj.LV_7.rds"),
  LV_8 = paste0(savepath_rds, "adj.LV_8.rds")
)

# Process datasets in a loop
results <- list()
for (name in names(dataset_paths)) {
  seurat_obj <- readRDS(dataset_paths[[name]])
  results[[name]] <- process_doublets(seurat_obj, name)
}
```
```{r merge_samples}
set.seed(123)
# Merge all eight clusters
chicken.organoid <- merge(adj.LV_1, y = c(adj.LV_2,adj.LV_3,adj.LV_4,adj.LV_5,adj.LV_6,adj.LV_7,adj.LV_8),
                       add.cell.ids = paste0("adj.LV_", 1:8),
                       project = "chicken.organoid",
                       merge.data = TRUE)
table(chicken.organoid$orig.ident) # Check sample identities in the merged dataset

# Run normalization -> findallmarkers
# Use Harmony to correct batch effect
chicken.organoid <- NormalizeData(chicken.organoid) %>% 
  FindVariableFeatures() %>% 
  ScaleData(model.use = "negbinom") %>% 
  RunPCA(verbose = FALSE) %>%
  RunHarmony(group.by.vars = "orig.ident", max.iter.harmony = 25, plot_convergence = T) %>%
  RunUMAP(reduction = "harmony", dims = 1:20) %>%
  FindNeighbors(reduction = "harmony", dims = 1:20) %>% 
  FindClusters()

UMAPPlot(chicken.organoid,label = T)

markers.chicken.organoid <- FindAllMarkers(chicken.organoid, logfc.threshmulti = 0.5,only.pos = T,min.pct = 0.2,assay = "RNA",
                                            max.cells.per.ident = 250,verbose = T)
View(markers.chicken.organoid)

chicken.organoid <- subset(chicken.organoid,idents=c(16,19,30),invert=T)
UMAPPlot(chicken.organoid,label=T)
saveRDS(chicken.organoid,paste(savepath_rds,"chicken.organoid.rds",sep =""))
```
```{r manual_annotation}
chicken.organoid <- JS_scaling(chicken.organoid)
chicken.organoid <- FindClusters(chicken.organoid,resolution = 2.5)
UMAPPlot(chicken.organoid,label=T)

markers.chicken.organoid <- FindAllMarkers(chicken.organoid, logfc.threshmulti = 0.5,only.pos = T,min.pct = 0.2,assay = "RNA",
                                            max.cells.per.ident = 250,verbose = T)
View(markers.chicken.organoid)
saveRDS(chicken.organoid,paste(savepath_rds,"chicken.organoid.v1.rds",sep =""))

chicken.organoid <- StashIdent(chicken.organoid, save.name = 'idents')
current.cluster.ids <- c(0:55)
chicken.organoid.ids <-  c("Mesenchymal cells","Mesenchymal cells","Mesenchymal cells","Mesenchymal cells","Mesenchymal cells","Mesenchymal cells",
                                   "Mesenchymal cells","Mesenchymal cells","Epithelial cells","Mesenchymal cells","Mesenchymal cells",
                                   "Epithelial cells","Mesenchymal cells","Epithelial cells","Epithelial cells","Mesenchymal cells",
                                   "Epithelial cells","Mesenchymal cells","Mesenchymal cells","Mesenchymal cells","Epithelial cells",
                                   "Mesenchymal cells","Mesenchymal cells","Epithelial cells","Mesenchymal cells","Epithelial cells",
                                   "Mesenchymal cells","Epithelial cells","Mesenchymal cells","Mesenchymal cells","Mesenchymal cells",
                                   "Mesenchymal cells","Epithelial cells","Mesenchymal cells","Mesenchymal cells","Epithelial cells",
                                   "Endothelial cells","Mesenchymal cells","Mesenchymal cells","Immune cells","Mesenchymal cells",
                                   "Epithelial cells","Epithelial cells","Mesenchymal cells","Neuron cells","Mesenchymal cells",
                                   "Immune cells","Epithelial cells","Mesenchymal cells","Mesenchymal cells","Epithelial cells",
                                   "Epithelial cells","Epithelial cells","Mesenchymal cells","Epithelial cells","Epithelial cells")
chicken.organoid@active.ident <- plyr::mapvalues(x = chicken.organoid@active.ident, from = current.cluster.ids, to = chicken.organoid.ids)
UMAPPlot(chicken.organoid,label = T)

markers.chicken.organoid <- FindAllMarkers(chicken.organoid, logfc.threshmulti = 0.5,only.pos = T,min.pct = 0.2,assay = "RNA",
                                            max.cells.per.ident = 250,verbose = T)
chicken.organoid@meta.data$celltype <- chicken.organoid@active.ident
View(markers.chicken.organoid)

# Generate a more detailed DEG table
markers.chicken.organoid <- FindAllMarkers(chicken.organoid,only.pos = T,max.cells.per.ident = 200,logfc.threshunique = 0.5,return.thresh = 0.05)
markers.chicken.organoid <- JS_expressiontable(chicken.organoid,markers.chicken.organoid)

saveRDS(chicken.organoid,paste(savepath_rds,"chicken.organoid.v2.rds",sep =""))
```
```{r proportion}

```